# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
github: https://github.com/biluo62

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics:
favicon: http://oiq00n80p.bkt.clouddn.com/favicons_2_16.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:

# header cube
cube_1: hankliu
cube_2: L
cube_3: X
cube_4: P
cube_5: C
cube_6: Y

# Author
# Your biography and your job is editable in each languages files in `languages` folder
author:
  name: hankliu
  desc: 我们在梦里走过许多路，醒来后却发现自己还在床上。
  email: 397694072@qq.com
  location: China
