# Header
menu:
  主页: /
  文章: /archives
  小工具: /toolkit
  小简介: /resume
  小关于: /about
rss: # /atom.xml
github: https://github.com/hankliu62

# Content
excerpt_link: Read More
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- archive

# Miscellaneous
wx_block: false
google_analytics:
favicon: /img/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# Duoshuo
duoshuo_shortname:

# Swiftype Search
swiftype_key:

# header cube
cube_1: HankLiu
cube_2: P
cube_3: X
cube_4: L
cube_5: C
cube_6: Y

# Author
# Your biography and your job is editable in each languages files in `languages` folder
author:
  name: HankLiu
  title: HankLiu的博客小屋
  desc: 努力去听风的声音，不必在意风的方向。
  email: 397694072@qq.com
  location: China
